name: Scrape Inburi Water Level

on:
  push:
    branches:
      - main
  schedule:
    # ตั้งเวลาให้รันทุกชั่วโมง (ที่นาทีที่ 0)
    - cron: '0 * * * *'
  workflow_dispatch: # เพิ่มปุ่มให้รันเองได้

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout โค้ดของคุณจาก Repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. ตั้งค่า Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. (สำคัญ) ติดตั้ง Google Chrome ลงใน Runner
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      
      # 4. ติดตั้งไลบรารีที่จำเป็น
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 5. รันสคริปต์ Python
      - name: Run scraper
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_TARGET_ID: ${{ secrets.LINE_TARGET_ID }}
        run: python inburi_scraper.py
      
      # 6. Commit ข้อมูลล่าสุด (ถ้าต้องการ)
      - name: Commit and push if data changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_inburi_data.txt
          # Commit และ Push เฉพาะเมื่อมีการเปลี่ยนแปลงในไฟล์เท่านั้น
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update last river data from Action" && git push)
