name: Scrape Inburi Water Level

on:
  push:
    branches:
      - main
  schedule:
    # ตั้งเวลาให้รันทุกชั่วโมง (ที่นาทีที่ 0)
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_TARGET_ID: ${{ secrets.LINE_TARGET_ID }}
        run: python inburi_scraper.py
      
      - name: Commit and push if data changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_inburi_data.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update last river data via API" && git push)
