name: Water Level Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper script
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_TARGET_ID: ${{ secrets.LINE_TARGET_ID }}
        run: python scraper.py

      - name: Commit and push if changed
        run: |
          if [ -f last_data.txt ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            # เพิ่มคำสั่ง git pull เข้ามาเพื่อให้ข้อมูลเป็นปัจจุบันก่อน push
            git pull
            git add last_data.txt
            git diff --quiet && git diff --staged --quiet || (git commit -m "Update last water data" && git push)
          else
            echo "last_data.txt not found, skipping commit."
          fi
