name: Weather Forecast Alert

on:
  workflow_dispatch:
  schedule:
    # รันทุกๆ 15 นาที
    - cron: '*/15 * * * *'

permissions:
  contents: write

jobs:
  forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weather forecast script
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_TARGET_ID: ${{ secrets.LINE_TARGET_ID }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: python weather_forecaster.py

     - name: Commit and push if changed
        run: |
          # แก้ไขให้เช็คไฟล์ที่ถูกต้อง คือ last_forecast_id.txt
          if [ -f last_forecast_id.txt ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git pull
            # แก้ไขให้เพิ่มไฟล์ที่ถูกต้อง คือ last_forecast_id.txt
            git add last_forecast_id.txt
            # แก้ไขข้อความ commit ให้สื่อความหมายมากขึ้น
            git diff --quiet && git diff --staged --quiet || (git commit -m "Update last forecast status" && git push)
          else
            # แก้ไขข้อความใน log ให้ตรงกัน
            echo "last_forecast_id.txt not found, skipping commit."
          fi
